import 'dart:convert';
import 'package:http/http.dart' as http;

Future<productDataList?> getPoductData(i) async {
  var url = 'http://want2u.duckdns.org/main/$i';

  var response = await http.get(
    Uri.parse(url),
  );

  productDataList? productList;
  final jsonResponse =
      json.decode(utf8.decode(response.bodyBytes)); //받은 정보를 json형태로 decode
  if (response.statusCode == 200) {
    productList = productDataList.fromJson(jsonResponse);
  } else {
    productList = null;
  }

  return productList;
}

class productDataList {
  List<Autogenerated>? productData;

  productDataList({this.productData});

  factory productDataList.fromJson(List<dynamic> json) {
    List<Autogenerated> getproductDataList = <Autogenerated>[];
    getproductDataList = json.map((i) => Autogenerated.fromJson(i)).toList();

    return new productDataList(productData: getproductDataList);
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.productData != null) {
      data['postList'] = this.productData!.map((v) => v.toJson()).toList();
    }

    return data;
  }
}

class Autogenerated {
  int? id;
  String? name;
  String? link;
  int? price;

  Autogenerated({this.id, this.name, this.link, this.price});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    link = json['link'];
    price = json['price'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['link'] = this.link;
    data['price'] = this.price;
    return data;
  }
}
